### ISSUE TITLE
match headers with current version of data dictionary

### ISSUE THREAD

**Issue by zachll** [Display-Lab/micca-validator#1]
Some columns required by the validator differ from the current data dictionary.

Here's the error message that should no longer appear:

Extra Headers: contraception_choice,immediate_method,contraception_provision,larc_provision
Missing Headers:contra_choice,imm_method,contra_prov,larc_prov

See current blank spreadsheet:
https://docs.google.com/spreadsheets/d/1Vk4WWSx5U2AF28FE2eMHKuCNW2Ea1I5-2bEGN7P5qCI/edit#gid=0

**Comment by grosscol** [comment]
contra_choice to contraception_choice
imm_method to immediate_method
contra_prov to contraception_provision
larc_prov to larc_provision
